os: Visual Studio 2017

build_script: 
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"
  - cmd: .\build.cmd All

test: off
version: '{build}'
artifacts:
  - path: build_output\*.nupkg
  - path: build_output\*.vsix
